name: Deployment to Firebase Hosting

on:
  push:
    branches: [ "main" ]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:
    steps:
      - name: Retrieving build from main
        uses: .github/workflows/ci.yml@main
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Production file
          path: ./artifacts/build

      # Install Firebase CLI
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/serviceAccountKey.json
          firebase deploy --project event-management-ui --token ${{ secrets.FIREBASE_TOKEN }}