name: Deployment to Firebase Hosting

on:
  workflow_run:
    workflows: ["Build Event Management UI"]  # The name of the CI workflow
    types:
      - completed  # Trigger only after the CI workflow is completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifact from CI
        uses: actions/download-artifact@v3
        with:
          name: Production file
          path: ./dist  # Path to store the downloaded build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --project event-management-ui --only hosting