name: Deployment to Firebase Hosting

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  build:
    name: Build
    uses: asyraphile/event-management-ui/.github/workflows/ci.yml@main
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy:
    name: Deploy to Firebase
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: List artifacts
        run: | 
          echo "Listing artifacts..."
          ls
      - name: Download build artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: Production file
          path: ./dist  # Path to store the downloaded build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --project event-management-ui --only hosting