name: Deployment to Firebase Hosting

on:
  workflow_run:
    workflows: ["Build Event Management UI"]
    types:
      - completed

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: poduction file
          path: ./artifacts/build

      # Install Firebase CLI
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/serviceAccountKey.json
          firebase deploy --project event-management-ui --token ${{ secrets.FIREBASE_TOKEN }}