name: Deployment to Firebase Hosting

on:
  push:
    branches: [ "main" ]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:
    steps:
      - name: Retrieving build from main
        uses: .github/workflows/ci.yml@main

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Production file  # Make sure this matches the artifact name from the build job
          path: ./dist  # Ensure this matches the actual location of your build output

      # Install Firebase CLI
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      # Authenticate using Firebase Token (preferred for simplicity)
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Make sure the token is set in GitHub Secrets
        run: |
          firebase deploy --project event-management-ui --only hosting