name: Deployment to Firebase Hosting

on: 
  pull_request:
    branches: [ "*" ]

permissions:
  checks: write
  contents: read
  pull-requests: write

Trigger deployment only after the CI workflow completes successfully on the main branch
on:
  workflow_run:
    workflows: ["Build Event Management UI"]  # Name of your CI workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/serviceAccountKey.json
          npm install -g firebase-tools
          firebase deploy --project event-management-ui --token ${{ secrets.FIREBASE_TOKEN }}
