name: Deployment to Firebase Hosting

on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
# Trigger deployment only after the CI workflow completes successfully on the main branch
on:
  workflow_run:
    workflows: ["Build Event Management UI"]  # Name of your CI workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_TOKEN }}
          channelId: live
          projectId: event-management-ui
