# Continuous Integration [build]

name: Build Event Management UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment for Angular
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x.x"

      # Clean Cache and Install project dependencies
      - name: Clean Cache and Install dependencies
        run: |
          npm cache clean --force
          npm install -g @angular/cli
          npm install

      # Build the Angular project
      - name: Build Angular app
        run: ng build

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # For GitHub actions
          firebaseServiceAccount: ${{ secrets.FIREBASE_TOKEN }}  # Use service account JSON
          channelId: live
          projectId: event-management-ui
